name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run tests (DEV/UAT/PROD)"
        required: true
        default: "DEV"
      browser:
        description: "Browser to run tests (chromium/firefox/webkit)"
        required: true
        default: "chromium"

jobs:
  test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set environment variables from secrets
        shell: pwsh
        run: |
          $env:ENV="${{ github.event.inputs.env }}"  # DEV/UAT/PROD
          $env:BROWSER="${{ github.event.inputs.browser }}"  # chromium/firefox/webkit

          if ($env:ENV -eq "DEV") {
            "BASE_URL=${{ secrets.DEV_URL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_EMAIL=${{ secrets.DEV_ADMIN_EMAIL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_PASSWORD=${{ secrets.DEV_ADMIN_PASSWORD }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } elseif ($env:ENV -eq "UAT") {
            "BASE_URL=${{ secrets.UAT_URL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_EMAIL=${{ secrets.UAT_ADMIN_EMAIL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_PASSWORD=${{ secrets.UAT_ADMIN_PASSWORD }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } elseif ($env:ENV -eq "PROD") {
            "BASE_URL=${{ secrets.PROD_URL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_EMAIL=${{ secrets.PROD_ADMIN_EMAIL }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            "ADMIN_PASSWORD=${{ secrets.PROD_ADMIN_PASSWORD }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

          "TEST_ENV=$env:ENV" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "BROWSER=$env:BROWSER" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Run Playwright tests
        shell: pwsh
        run: |
          echo "Running tests on $env:TEST_ENV in browser $env:BROWSER ($env:BASE_URL)"
          npx playwright test --reporter=html

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
