name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        env: [DEV]
        browser: [chromium, firefox, webkit]

    timeout-minutes: 60

    env:
      BASE_URL: ${{ secrets.DEV_URL }}
      ADMIN_EMAIL: ${{ secrets.DEV_ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.DEV_ADMIN_PASSWORD }}
      TEST_ENV: ${{ matrix.env }}
      BROWSER: ${{ matrix.browser }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        shell: bash
        run: |
          echo "Running tests on $TEST_ENV in browser $BROWSER ($BASE_URL)"
          npx playwright test --browser=$BROWSER --reporter=html

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.env }}-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30
